"""CrawlState 抽象接口 (PEP 544 Protocol)。

按 ISP 拆分为三个窄接口：
- CrawlStateReader — 只读查询（Engine / Stats 公用）
- CrawlStateWriter — DB 写入 + 队列/in_flight 操作（Engine 使用）
- CrawlStateAdmin — 深度/迁移管理（恢复路径专用）

CrawlState 无需显式继承——结构子类型按鸭子类型自动匹配。
新增存储后端只需实现所需接口即可作为 CrawlState 的替代适配器。
"""

from __future__ import annotations

from typing import Dict, List, Optional, Protocol, Tuple

from astrocrawl._types import EnqueueResult


class CrawlStateConfig(Protocol):
    """CrawlState 需要的配置字段（ISP 窄接口）。"""

    queue_hard_maxsize: int
    max_requeue: int


class CrawlStateReader(Protocol):
    """只读查询 — Engine / Stats 公用。"""

    db_path: str

    async def completed_count(self) -> int: ...
    async def failure_count(self) -> int: ...
    async def retryable_failure_count(self, max_requeue: int) -> int: ...
    async def permanent_failure_count(self, max_requeue: int) -> int: ...
    async def counts_by_outcome(self) -> Dict[str, int]: ...
    async def peek_retryable(self, max_requeue: int) -> Optional[Tuple[str, int, int]]: ...
    async def completed_count_by_depth(self) -> Dict[int, int]: ...
    async def failed_count_by_depth(self) -> Dict[int, int]: ...
    async def urls_table_empty(self) -> bool: ...
    async def get_meta(self, key: str, default: str = "") -> str: ...
    async def queue_count_by_depth(self) -> Dict[int, int]: ...


class CrawlStateWriter(Protocol):
    """DB 写入 + 队列/in_flight 操作 — Engine 使用。"""

    async def mark_completed(self, url: str, depth: int = 0, original_url: str = "", outcome: str = "") -> bool: ...
    async def add_content_hash(self, h: str, url: str = "") -> bool: ...
    async def log_failure(self, url: str, depth: int, error: str, permanent: bool = False) -> None: ...
    async def set_meta(self, key: str, value: str) -> None: ...
    async def reset_all(self) -> None: ...
    # 队列操作
    async def push_to_queue_single(self, url: str, depth: int, domain: str = "") -> EnqueueResult: ...
    async def push_to_queue_as_owner(self, url: str, depth: int, domain: str = "") -> bool: ...
    async def try_schedule_retry(self, url: str, depth: int) -> bool: ...
    async def pop_from_domain(self, domain: str) -> Optional[Tuple[str, int]]: ...
    async def get_active_domains(self) -> List[str]: ...
    async def queue_size(self) -> int: ...
    async def wait_for_queue(self, timeout: float = 0.5) -> None: ...
    async def is_queue_full(self) -> bool: ...
    # in_flight 操作
    async def in_flight_count(self) -> int: ...
    async def url_in_flight(self, url: str) -> bool: ...
    async def force_fail_all_in_flight(self, max_requeue: int) -> int: ...
    async def atomic_retry_reclaim(self, max_requeue: int) -> Optional[Tuple[str, int]]: ...


class CrawlStateAdmin(Protocol):
    """深度/迁移管理 — 恢复路径专用。"""

    async def promote_boundary_links(self, new_depth: int) -> List[Tuple[str, int]]: ...
    async def save_boundary_links(self, parent_url: str, child_urls: list, parent_depth: int) -> int: ...
    async def get_lost_children(self, parent_depth: int) -> List[str]: ...
    async def purge_failures_depth_ge(self, max_depth: int) -> int: ...
    async def purge_queue_depth_ge(self, max_depth: int) -> int: ...
    async def clean_content_hashes(self, cutoff: float) -> None: ...
    async def boundary_links_count(self) -> int: ...
    async def reset_queue_only(self) -> None: ...
    async def purge_orphaned_queue_entries(self) -> int: ...


class CrawlStateProtocol(CrawlStateReader, CrawlStateWriter, CrawlStateAdmin, Protocol):
    """完整 CrawlState 接口（生命周期 + 三个窄接口的组合）。"""

    async def open(self) -> None: ...
    async def close(self) -> None: ...
    async def flush(self) -> None:
        """确保所有待处理写入持久化到存储。（协议桩，CrawlState 有自己的实现。）"""
        ...
